version: '3'

services:
  mongo:
    volumes:
      - ./data:/data/db
  app:
    container_name: ts-node-app-prod
    volumes:      
      - ./src:/usr/prod/app/src
      - ./images:/usr/prod/app/images
      - ./keys:/usr/prod/app/keys
      - ./signatures:/usr/prod/app/signatures
      - .env:/usr/prod/app/.env
      - ./images_test:/usr/prod/app/images_test
    build: 
      target: production
    command: yarn start
