version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.1-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - backend
  app:
    container_name: ts-node-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment: 
      - MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/cloud-encrypt?retryWrites=true&w=majority&directConnection=true&authSource=admin
      - CLIENT_URL=${CLIENT_URL}
    links: 
      - mongo  
    depends_on:
      - mongo  
    networks:
      - backend

networks:
  backend:
    driver: bridge
