# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PORT: 3000
  MONGODB_URL: mongodb://127.0.0.1:27017/node-ts-boilerplate
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10
  CLIENT_URL: http://localhost:3000

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  # test:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #       mongodb-version: [4.0]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Start MongoDB
  #     uses: supercharge/mongodb-github-action@1.3.0
  #     with:
  #       mongodb-version: ${{ matrix.mongodb-version }}
  #   - run: yarn
  #   - name: Run linting tests
  #     run: yarn lint
  #   - name: Run unit tests
  #     run: yarn test

  # coverage:

  #   runs-on: ubuntu-latest

  #   needs: test

  #   strategy:
  #     matrix:
  #       node-version: [14.x]
  #       mongodb-version: [4.0]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Start MongoDB
  #     uses: supercharge/mongodb-github-action@1.3.0
  #     with:
  #       mongodb-version: ${{ matrix.mongodb-version }}
  #   - run: yarn
  #   - name: Generate coverage
  #     run: yarn coverage:coveralls
  #   - name: Upload coverage to Codecov
  #     uses: codecov/codecov-action@v2
  #     with:
  #       fail_ci_if_error: true
